export type PageType = 'pillar' | 'supporting' | 'blog' | 'industry' | 'cost';
export type Cluster = 'k1' | 'k2' | 'k3' | 'k4' | 'k5' | 'k6' | 'k7';

export interface RouteConfig {
  path: string;
  slug: string;
  type: PageType;
  cluster: Cluster;
  priority: 'P0' | 'P1' | 'P2' | 'P3';
  metaTitle: string;
  metaDescription: string;
  h1: string;
  parentPath?: string;
  parentLabel?: string;
}

export const SITE_URL = 'https://wefutura.com';

export const pillarRoutes: RouteConfig[] = [
  {
    path: '/uslugi/automatyzacja-procesow-biznesowych',
    slug: 'automatyzacja-procesow-biznesowych',
    type: 'pillar',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'Automatyzacja Procesów Biznesowych | WeFutura',
    metaDescription: 'Automatyzacja procesów biznesowych dla firm — wdrożenia RPA, BPA i BPMS. Oszczędź 20+ godzin tygodniowo. Bezpłatny audyt procesów.',
    h1: 'Automatyzacja Procesów Biznesowych',
    parentPath: '/uslugi',
    parentLabel: 'Usługi',
  },
  {
    path: '/uslugi/automatyzacja-no-code',
    slug: 'automatyzacja-no-code',
    type: 'pillar',
    cluster: 'k2',
    priority: 'P0',
    metaTitle: 'Automatyzacja No-Code i Low-Code | Make, n8n, Zapier | WeFutura',
    metaDescription: 'Automatyzacja no-code dla firm — wdrożenia Make, n8n, Zapier, Power Automate. Integracje bez programowania. Bezpłatna konsultacja.',
    h1: 'Automatyzacja No-Code dla Firm',
    parentPath: '/uslugi',
    parentLabel: 'Usługi',
  },
  {
    path: '/uslugi/automatyzacja-sprzedazy-i-marketingu',
    slug: 'automatyzacja-sprzedazy-i-marketingu',
    type: 'pillar',
    cluster: 'k3',
    priority: 'P0',
    metaTitle: 'Automatyzacja Sprzedaży i Marketingu | WeFutura',
    metaDescription: 'Automatyzacja sprzedaży i marketingu — wdrożenia CRM, Pipedrive, HubSpot, kampanie marketing automation. Zwiększ konwersję bez dodatkowego zespołu.',
    h1: 'Automatyzacja Sprzedaży i Marketingu',
    parentPath: '/uslugi',
    parentLabel: 'Usługi',
  },
  {
    path: '/uslugi/systemy-ai-dla-firm',
    slug: 'systemy-ai-dla-firm',
    type: 'pillar',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'Systemy AI dla Firm — Wdrożenia na Zamówienie | WeFutura',
    metaDescription: 'Systemy AI dla firm — chatboty, OCR, LLM, kwalifikacja leadów. Projektujemy AI dopasowane do Twojego biznesu. Bezpłatna konsultacja.',
    h1: 'Systemy AI dla Firm',
    parentPath: '/uslugi',
    parentLabel: 'Usługi',
  },
];

export const supportingRoutes: RouteConfig[] = [
  {
    path: '/uslugi/rpa',
    slug: 'rpa',
    type: 'supporting',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'RPA — Robotic Process Automation | WeFutura',
    metaDescription: 'Wdrożenia RPA (Robotic Process Automation) dla firm. Automatyzacja powtarzalnych zadań bez kodu. ROI w 2–3 miesiące.',
    h1: 'RPA — Robotic Process Automation',
    parentPath: '/uslugi/automatyzacja-procesow-biznesowych',
    parentLabel: 'Automatyzacja Procesów',
  },
  {
    path: '/uslugi/bpa',
    slug: 'bpa',
    type: 'supporting',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'BPA — Business Process Automation | WeFutura',
    metaDescription: 'BPA (Business Process Automation) — automatyzacja procesów biznesowych klasy enterprise. Integracje, przepływy pracy, redukcja błędów ludzkich.',
    h1: 'BPA — Business Process Automation',
    parentPath: '/uslugi/automatyzacja-procesow-biznesowych',
    parentLabel: 'Automatyzacja Procesów',
  },
  {
    path: '/uslugi/bpms',
    slug: 'bpms',
    type: 'supporting',
    cluster: 'k1',
    priority: 'P1',
    metaTitle: 'BPMS — Zarządzanie Procesami Biznesowymi | WeFutura',
    metaDescription: 'BPMS (Business Process Management System) — systemy zarządzania procesami dla firm. Modelowanie, monitoring i optymalizacja procesów.',
    h1: 'BPMS — System Zarządzania Procesami',
    parentPath: '/uslugi/automatyzacja-procesow-biznesowych',
    parentLabel: 'Automatyzacja Procesów',
  },
  {
    path: '/uslugi/audyt-i-optymalizacja-kosztow',
    slug: 'audyt-i-optymalizacja-kosztow',
    type: 'supporting',
    cluster: 'k1',
    priority: 'P1',
    metaTitle: 'Audyt i Optymalizacja Procesów | WeFutura',
    metaDescription: 'Audyt procesów biznesowych i optymalizacja kosztów operacyjnych. Identyfikujemy co automatyzować, żebyś oszczędzał czas i pieniądze.',
    h1: 'Audyt i Optymalizacja Procesów',
    parentPath: '/uslugi/automatyzacja-procesow-biznesowych',
    parentLabel: 'Automatyzacja Procesów',
  },
  {
    path: '/uslugi/wdrozenia-make-com',
    slug: 'wdrozenia-make-com',
    type: 'supporting',
    cluster: 'k2',
    priority: 'P0',
    metaTitle: 'Wdrożenia Make.com (Integromat) dla Firm | WeFutura',
    metaDescription: 'Wdrożenia Make.com dla firm — automatyzacja scenariuszy, integracje API, workflow bez kodu. Certyfikowani partnerzy Make.',
    h1: 'Wdrożenia Make.com dla Firm',
    parentPath: '/uslugi/automatyzacja-no-code',
    parentLabel: 'Automatyzacja No-Code',
  },
  {
    path: '/uslugi/wdrozenia-n8n',
    slug: 'wdrozenia-n8n',
    type: 'supporting',
    cluster: 'k2',
    priority: 'P0',
    metaTitle: 'Wdrożenia n8n — Workflow Automation | WeFutura',
    metaDescription: 'Wdrożenia n8n dla firm — open-source workflow automation. Własna infrastruktura, pełna kontrola danych, integracje z setkami systemów.',
    h1: 'Wdrożenia n8n dla Firm',
    parentPath: '/uslugi/automatyzacja-no-code',
    parentLabel: 'Automatyzacja No-Code',
  },
  {
    path: '/uslugi/integracje-zapier',
    slug: 'integracje-zapier',
    type: 'supporting',
    cluster: 'k2',
    priority: 'P1',
    metaTitle: 'Integracje Zapier dla Firm | WeFutura',
    metaDescription: 'Integracje Zapier dla firm — automatyczne połączenia między aplikacjami, zapisy danych, powiadomienia. Konfiguracja i optymalizacja Zapów.',
    h1: 'Integracje Zapier dla Firm',
    parentPath: '/uslugi/automatyzacja-no-code',
    parentLabel: 'Automatyzacja No-Code',
  },
  {
    path: '/uslugi/power-automate-wdrozenia',
    slug: 'power-automate-wdrozenia',
    type: 'supporting',
    cluster: 'k2',
    priority: 'P1',
    metaTitle: 'Power Automate Wdrożenia dla Firm | WeFutura',
    metaDescription: 'Wdrożenia Microsoft Power Automate dla firm korzystających z Microsoft 365. Automatyzacja Teams, SharePoint, Excel, Outlook.',
    h1: 'Power Automate — Wdrożenia dla Firm',
    parentPath: '/uslugi/automatyzacja-no-code',
    parentLabel: 'Automatyzacja No-Code',
  },
  {
    path: '/uslugi/integracje-crm-erp',
    slug: 'integracje-crm-erp',
    type: 'supporting',
    cluster: 'k2',
    priority: 'P0',
    metaTitle: 'Integracje CRM i ERP | WeFutura',
    metaDescription: 'Integracje systemów CRM i ERP — łączymy Twoje systemy w jeden ekosystem. Eliminujemy ręczne przepisywanie danych i błędy.',
    h1: 'Integracje CRM i ERP',
    parentPath: '/uslugi/automatyzacja-no-code',
    parentLabel: 'Automatyzacja No-Code',
  },
  {
    path: '/uslugi/wdrozenia-crm',
    slug: 'wdrozenia-crm',
    type: 'supporting',
    cluster: 'k3',
    priority: 'P0',
    metaTitle: 'Wdrożenia CRM dla Firm | WeFutura',
    metaDescription: 'Wdrożenia systemów CRM dopasowane do Twojej sprzedaży. Konfiguracja, migracja danych, szkolenie zespołu. Sprawdź które CRM pasuje do Ciebie.',
    h1: 'Wdrożenia CRM dla Firm',
    parentPath: '/uslugi/automatyzacja-sprzedazy-i-marketingu',
    parentLabel: 'Automatyzacja Sprzedaży',
  },
  {
    path: '/uslugi/wdrozenia-pipedrive',
    slug: 'wdrozenia-pipedrive',
    type: 'supporting',
    cluster: 'k3',
    priority: 'P1',
    metaTitle: 'Wdrożenia Pipedrive dla Firm | WeFutura',
    metaDescription: 'Wdrożenia Pipedrive — konfiguracja lejka sprzedaży, automatyzacje, integracje z e-mailem i narzędziami marketingowymi.',
    h1: 'Wdrożenia Pipedrive dla Firm',
    parentPath: '/uslugi/automatyzacja-sprzedazy-i-marketingu',
    parentLabel: 'Automatyzacja Sprzedaży',
  },
  {
    path: '/uslugi/wdrozenia-hubspot',
    slug: 'wdrozenia-hubspot',
    type: 'supporting',
    cluster: 'k3',
    priority: 'P1',
    metaTitle: 'Wdrożenia HubSpot dla Firm | WeFutura',
    metaDescription: 'Wdrożenia HubSpot CRM i Marketing Hub — konfiguracja, automatyzacje marketingowe, integracje. Pełne wsparcie po wdrożeniu.',
    h1: 'Wdrożenia HubSpot dla Firm',
    parentPath: '/uslugi/automatyzacja-sprzedazy-i-marketingu',
    parentLabel: 'Automatyzacja Sprzedaży',
  },
  {
    path: '/uslugi/automatyzacja-marketingu',
    slug: 'automatyzacja-marketingu',
    type: 'supporting',
    cluster: 'k3',
    priority: 'P0',
    metaTitle: 'Automatyzacja Marketingu dla Firm | WeFutura',
    metaDescription: 'Automatyzacja marketingu — kampanie email, segmentacja leadów, lead nurturing, integracja z CRM. Więcej konwersji przy mniejszym wysiłku.',
    h1: 'Automatyzacja Marketingu',
    parentPath: '/uslugi/automatyzacja-sprzedazy-i-marketingu',
    parentLabel: 'Automatyzacja Sprzedaży',
  },
  {
    path: '/uslugi/chatbot-ai-dla-firm',
    slug: 'chatbot-ai-dla-firm',
    type: 'supporting',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'Chatbot AI dla Firm — Wdrożenia na Zamówienie | WeFutura',
    metaDescription: 'Chatbot AI dla firm — obsługa klienta 24/7, kwalifikacja leadów, automatyczne odpowiedzi. Projektujemy chatboty dopasowane do Twojego biznesu.',
    h1: 'Chatbot AI dla Firm',
    parentPath: '/uslugi/systemy-ai-dla-firm',
    parentLabel: 'Systemy AI',
  },
  {
    path: '/uslugi/projektowanie-systemow-ai',
    slug: 'projektowanie-systemow-ai',
    type: 'supporting',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'Projektowanie Systemów AI na Zamówienie | WeFutura',
    metaDescription: 'Projektowanie systemów AI na zamówienie — architektury AI, integracje z istniejącymi systemami, własne modele. Nie gotowce, tylko rozwiązania szyte na miarę.',
    h1: 'Projektowanie Systemów AI na Zamówienie',
    parentPath: '/uslugi/systemy-ai-dla-firm',
    parentLabel: 'Systemy AI',
  },
  {
    path: '/uslugi/systemy-ocr',
    slug: 'systemy-ocr',
    type: 'supporting',
    cluster: 'k4',
    priority: 'P1',
    metaTitle: 'Systemy OCR — Automatyczne Rozpoznawanie Tekstu | WeFutura',
    metaDescription: 'Systemy OCR dla firm — automatyczne odczytywanie faktur, umów, formularzy. Eliminacja ręcznego przepisywania danych. Integracja z ERP i CRM.',
    h1: 'Systemy OCR dla Firm',
    parentPath: '/uslugi/systemy-ai-dla-firm',
    parentLabel: 'Systemy AI',
  },
  {
    path: '/uslugi/ai-komunikacja-i-lead-triage',
    slug: 'ai-komunikacja-i-lead-triage',
    type: 'supporting',
    cluster: 'k4',
    priority: 'P1',
    metaTitle: 'AI Kwalifikacja Leadów i Komunikacja | WeFutura',
    metaDescription: 'Automatyczna kwalifikacja leadów z AI — scoring, kategoryzacja zapytań, routing do właściwych działów. Skróć czas odpowiedzi i zwiększ konwersję.',
    h1: 'AI Kwalifikacja Leadów i Automatyczna Komunikacja',
    parentPath: '/uslugi/systemy-ai-dla-firm',
    parentLabel: 'Systemy AI',
  },
  {
    path: '/uslugi/wdrozenia-llm-w-firmie',
    slug: 'wdrozenia-llm-w-firmie',
    type: 'supporting',
    cluster: 'k4',
    priority: 'P1',
    metaTitle: 'Wdrożenia LLM dla Firm — Duże Modele Językowe | WeFutura',
    metaDescription: 'Wdrożenia LLM (Large Language Models) dla firm — GPT, Claude, Llama. Własne asystenty AI, automatyczne streszczenia, analiza dokumentów.',
    h1: 'Wdrożenia LLM w Firmie',
    parentPath: '/uslugi/systemy-ai-dla-firm',
    parentLabel: 'Systemy AI',
  },
];

export const industryRoutes: RouteConfig[] = [
  {
    path: '/rozwiazania/automatyzacja-dla-ecommerce',
    slug: 'automatyzacja-dla-ecommerce',
    type: 'industry',
    cluster: 'k5',
    priority: 'P2',
    metaTitle: 'Automatyzacja dla E-commerce | WeFutura',
    metaDescription: 'Automatyzacja procesów dla sklepów e-commerce — obsługa zamówień, synchronizacja stanów, obsługa zwrotów, automatyczne faktury.',
    h1: 'Automatyzacja dla E-commerce',
    parentPath: '/rozwiazania',
    parentLabel: 'Rozwiązania',
  },
  {
    path: '/rozwiazania/automatyzacja-dla-agencji-marketingowych',
    slug: 'automatyzacja-dla-agencji-marketingowych',
    type: 'industry',
    cluster: 'k5',
    priority: 'P2',
    metaTitle: 'Automatyzacja dla Agencji Marketingowych | WeFutura',
    metaDescription: 'Automatyzacja dla agencji marketingowych — raportowanie, onboarding klientów, harmonogramy kampanii, integracje z platformami reklamowymi.',
    h1: 'Automatyzacja dla Agencji Marketingowych',
    parentPath: '/rozwiazania',
    parentLabel: 'Rozwiązania',
  },
  {
    path: '/rozwiazania/automatyzacja-dla-logistyki',
    slug: 'automatyzacja-dla-logistyki',
    type: 'industry',
    cluster: 'k5',
    priority: 'P2',
    metaTitle: 'Automatyzacja dla Logistyki i Transportu | WeFutura',
    metaDescription: 'Automatyzacja procesów logistycznych — śledzenie przesyłek, zarządzanie magazynem, dokumentacja transportowa, powiadomienia klientów.',
    h1: 'Automatyzacja dla Logistyki',
    parentPath: '/rozwiazania',
    parentLabel: 'Rozwiązania',
  },
  {
    path: '/rozwiazania/automatyzacja-dla-biur-rachunkowych',
    slug: 'automatyzacja-dla-biur-rachunkowych',
    type: 'industry',
    cluster: 'k5',
    priority: 'P2',
    metaTitle: 'Automatyzacja dla Biur Rachunkowych | WeFutura',
    metaDescription: 'Automatyzacja dla biur rachunkowych — OCR faktur, import do systemów księgowych, przypomnienia płatności, generowanie raportów.',
    h1: 'Automatyzacja dla Biur Rachunkowych',
    parentPath: '/rozwiazania',
    parentLabel: 'Rozwiązania',
  },
  {
    path: '/rozwiazania/automatyzacja-dla-firm-produkcyjnych',
    slug: 'automatyzacja-dla-firm-produkcyjnych',
    type: 'industry',
    cluster: 'k5',
    priority: 'P2',
    metaTitle: 'Automatyzacja dla Firm Produkcyjnych | WeFutura',
    metaDescription: 'Automatyzacja procesów w produkcji — planowanie zleceń, kontrola jakości, zarządzanie magazynem komponentów, raportowanie wydajności.',
    h1: 'Automatyzacja dla Firm Produkcyjnych',
    parentPath: '/rozwiazania',
    parentLabel: 'Rozwiązania',
  },
];

export const costRoutes: RouteConfig[] = [
  {
    path: '/koszty-automatyzacji',
    slug: 'koszty-automatyzacji',
    type: 'cost',
    cluster: 'k7',
    priority: 'P1',
    metaTitle: 'Ile Kosztuje Automatyzacja Procesów? | WeFutura',
    metaDescription: 'Ile kosztuje automatyzacja procesów biznesowych w 2026? Przejrzyste ceny, modele rozliczenia, ROI kalkulator. Bezpłatna wycena w 24h.',
    h1: 'Ile Kosztuje Automatyzacja Procesów Biznesowych?',
  },
];

export const blogRoutes: RouteConfig[] = [
  {
    path: '/blog/co-to-jest-rpa',
    slug: 'co-to-jest-rpa',
    type: 'blog',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'Co to jest RPA? Robotic Process Automation — Przewodnik 2026 | WeFutura',
    metaDescription: 'Co to jest RPA (Robotic Process Automation)? Jak działa, kiedy wdrożyć, jakie procesy automatyzuje. Praktyczny przewodnik z przykładami dla firm.',
    h1: 'Co to jest RPA? Kompletny Przewodnik po Robotic Process Automation',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/automatyzacja-procesow-co-to-jest',
    slug: 'automatyzacja-procesow-co-to-jest',
    type: 'blog',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'Automatyzacja Procesów Biznesowych — Co to Jest i Od Czego Zacząć | WeFutura',
    metaDescription: 'Automatyzacja procesów biznesowych — czym jest, jakie procesy warto automatyzować, jak zacząć. Praktyczne wskazówki dla firm każdej wielkości.',
    h1: 'Automatyzacja Procesów Biznesowych — Co to Jest i Od Czego Zacząć',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/digitalizacja-firmy-od-czego-zaczac',
    slug: 'digitalizacja-firmy-od-czego-zaczac',
    type: 'blog',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'Digitalizacja Firmy — Od Czego Zacząć w 2026 | WeFutura',
    metaDescription: 'Digitalizacja firmy krok po kroku — co digitalizować pierwsze, jakie narzędzia wybrać, jak uniknąć typowych błędów. Praktyczny przewodnik 2026.',
    h1: 'Digitalizacja Firmy — Od Czego Zacząć',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/robotyzacja-procesow-przewodnik',
    slug: 'robotyzacja-procesow-przewodnik',
    type: 'blog',
    cluster: 'k1',
    priority: 'P0',
    metaTitle: 'Robotyzacja Procesów Biznesowych — Przewodnik | WeFutura',
    metaDescription: 'Robotyzacja procesów biznesowych — czym różni się od automatyzacji, jak wdrożyć, przykłady robotów software w firmach produkcyjnych i usługowych.',
    h1: 'Robotyzacja Procesów Biznesowych — Przewodnik',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/transformacja-cyfrowa-przewodnik',
    slug: 'transformacja-cyfrowa-przewodnik',
    type: 'blog',
    cluster: 'k1',
    priority: 'P1',
    metaTitle: 'Transformacja Cyfrowa Firmy — Przewodnik 2026 | WeFutura',
    metaDescription: 'Transformacja cyfrowa — co to znaczy w praktyce, jak ją przeprowadzić krok po kroku, jakie błędy popełniają firmy i jak ich uniknąć.',
    h1: 'Transformacja Cyfrowa Firmy — Praktyczny Przewodnik',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/make-vs-zapier-porownanie',
    slug: 'make-vs-zapier-porownanie',
    type: 'blog',
    cluster: 'k2',
    priority: 'P0',
    metaTitle: 'Make vs Zapier — Porównanie 2026 | Które Wybrać? | WeFutura',
    metaDescription: 'Make vs Zapier — szczegółowe porównanie funkcji, cen i możliwości. Które narzędzie no-code wybrać dla Twojej firmy w 2026?',
    h1: 'Make vs Zapier — Porównanie i Które Wybrać',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/n8n-vs-make-co-wybrac',
    slug: 'n8n-vs-make-co-wybrac',
    type: 'blog',
    cluster: 'k2',
    priority: 'P0',
    metaTitle: 'n8n vs Make — Co Wybrać dla Twojej Firmy? | WeFutura',
    metaDescription: 'n8n vs Make — porównanie open-source vs SaaS. Koszty, możliwości, bezpieczeństwo danych, krzywa uczenia. Który wybrać w 2026?',
    h1: 'n8n vs Make — Które Narzędzie Wybrać?',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/uipath-co-to-jest-rpa',
    slug: 'uipath-co-to-jest-rpa',
    type: 'blog',
    cluster: 'k2',
    priority: 'P1',
    metaTitle: 'UiPath — Co to Jest i Jak Działa RPA? | WeFutura',
    metaDescription: 'UiPath — co to jest, jak działa, dla kogo jest przeznaczony. Porównanie z innymi platformami RPA. Kiedy warto wdrożyć UiPath w firmie.',
    h1: 'UiPath — Co to Jest i Jak Działa?',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/workflow-automatyzacja-przyklady',
    slug: 'workflow-automatyzacja-przyklady',
    type: 'blog',
    cluster: 'k2',
    priority: 'P2',
    metaTitle: 'Workflow — Automatyzacja z Przykładami dla Firm | WeFutura',
    metaDescription: 'Workflow automation — co to jest, jak projektować przepływy pracy, przykłady automatyzacji workflow w sprzedaży, HR i obsłudze klienta.',
    h1: 'Workflow — Czym Jest i Jak Automatyzować Przepływy Pracy',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/lejek-sprzedazowy-jak-zautomatyzowac',
    slug: 'lejek-sprzedazowy-jak-zautomatyzowac',
    type: 'blog',
    cluster: 'k3',
    priority: 'P0',
    metaTitle: 'Lejek Sprzedażowy — Jak Zautomatyzować | WeFutura',
    metaDescription: 'Jak zautomatyzować lejek sprzedażowy — od pozyskania leada do zamknięcia transakcji. Narzędzia, schematy, przykłady wdrożeń B2B.',
    h1: 'Lejek Sprzedażowy — Jak Zautomatyzować Krok po Kroku',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/jak-wybrac-crm-dla-firmy',
    slug: 'jak-wybrac-crm-dla-firmy',
    type: 'blog',
    cluster: 'k3',
    priority: 'P1',
    metaTitle: 'Jaki CRM Wybrać dla Firmy? Przewodnik 2026 | WeFutura',
    metaDescription: 'Jak wybrać CRM dla firmy — porównanie systemów, kryteria wyboru, ceny, dla kogo który CRM. Praktyczny poradnik dla MŚP.',
    h1: 'Jaki CRM Wybrać dla Firmy? Kompletny Przewodnik',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/salesmanago-co-to-jest',
    slug: 'salesmanago-co-to-jest',
    type: 'blog',
    cluster: 'k3',
    priority: 'P1',
    metaTitle: 'SALESmanago — Co to Jest i Jak Działa? | WeFutura',
    metaDescription: 'SALESmanago — co to jest, jak działa marketing automation, jakie funkcje oferuje. Dla kogo jest SALESmanago i kiedy warto je wdrożyć.',
    h1: 'SALESmanago — Co to Jest i Jak Działa Marketing Automation',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/ai-sztuczna-inteligencja-w-biznesie',
    slug: 'ai-sztuczna-inteligencja-w-biznesie',
    type: 'blog',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'AI — Sztuczna Inteligencja w Biznesie | WeFutura',
    metaDescription: 'AI w biznesie — jak sztuczna inteligencja zmienia firmy, praktyczne zastosowania, jak zacząć wdrożenie. Przewodnik dla kadry zarządzającej.',
    h1: 'AI — Sztuczna Inteligencja w Biznesie. Praktyczny Przewodnik',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/llm-co-to-jest-duze-modele-jezykowe',
    slug: 'llm-co-to-jest-duze-modele-jezykowe',
    type: 'blog',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'LLM — Co to Jest? Duże Modele Językowe Wyjaśnione | WeFutura',
    metaDescription: 'LLM (Large Language Models) — co to jest, jak działają, jak GPT, Claude i inne modele językowe można wykorzystać w firmie. Prosty przewodnik.',
    h1: 'LLM — Co to Jest? Duże Modele Językowe Wyjaśnione',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/chatbot-ai-dla-firmy-jak-wdrozyc',
    slug: 'chatbot-ai-dla-firmy-jak-wdrozyc',
    type: 'blog',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'Chatbot AI dla Firmy — Jak Wdrożyć Krok po Kroku | WeFutura',
    metaDescription: 'Jak wdrożyć chatbot AI w firmie — wybór technologii, konfiguracja, integracja z systemami. Praktyczny przewodnik z przykładami wdrożeń.',
    h1: 'Chatbot AI dla Firmy — Jak Wdrożyć Krok po Kroku',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/narzedzia-ai-dla-firm-przeglad',
    slug: 'narzedzia-ai-dla-firm-przeglad',
    type: 'blog',
    cluster: 'k4',
    priority: 'P0',
    metaTitle: 'Narzędzia AI dla Firm — Przegląd 2026 | WeFutura',
    metaDescription: 'Najlepsze narzędzia AI dla firm w 2026 — przegląd, porównanie, dla kogo i do czego. ChatGPT, Claude, Gemini i inne w zastosowaniach biznesowych.',
    h1: 'Narzędzia AI dla Firm — Przegląd i Porównanie 2026',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/ocr-co-to-jest-rozpoznawanie-tekstu',
    slug: 'ocr-co-to-jest-rozpoznawanie-tekstu',
    type: 'blog',
    cluster: 'k4',
    priority: 'P1',
    metaTitle: 'OCR — Co to Jest? Rozpoznawanie Tekstu w Firmie | WeFutura',
    metaDescription: 'OCR (Optical Character Recognition) — co to jest, jak działa, jakie dokumenty przetwarza. Zastosowania OCR w księgowości, logistyce i produkcji.',
    h1: 'OCR — Co to Jest i Jak Działa Rozpoznawanie Tekstu',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/wdrozenie-ai-krok-po-kroku',
    slug: 'wdrozenie-ai-krok-po-kroku',
    type: 'blog',
    cluster: 'k4',
    priority: 'P1',
    metaTitle: 'Wdrożenie AI w Firmie — Krok po Kroku | WeFutura',
    metaDescription: 'Jak wdrożyć AI w firmie krok po kroku — od audytu procesów do uruchomienia systemu. Harmonogram, koszty, ryzyka i jak je minimalizować.',
    h1: 'Jak Wdrożyć AI w Firmie — Krok po Kroku',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/chatbot-vs-voicebot-roznice',
    slug: 'chatbot-vs-voicebot-roznice',
    type: 'blog',
    cluster: 'k4',
    priority: 'P2',
    metaTitle: 'Chatbot vs Voicebot — Różnice i Kiedy Który Wybrać | WeFutura',
    metaDescription: 'Chatbot vs voicebot — czym się różnią, jakie mają zastosowania, który wybrać dla swojego biznesu. Porównanie z przykładami wdrożeń.',
    h1: 'Chatbot vs Voicebot — Różnice i Kiedy Który Wybrać',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/ai-w-obsludze-klienta-przyklady',
    slug: 'ai-w-obsludze-klienta-przyklady',
    type: 'blog',
    cluster: 'k4',
    priority: 'P2',
    metaTitle: 'AI w Obsłudze Klienta — Przykłady Wdrożeń | WeFutura',
    metaDescription: 'AI w obsłudze klienta — przykłady wdrożeń, chatboty, automatyczne odpowiedzi, analiza sentymentu. Jak AI zmniejsza koszty obsługi i zwiększa satysfakcję.',
    h1: 'AI w Obsłudze Klienta — Przykłady i Wdrożenia',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/pipedrive-vs-hubspot',
    slug: 'pipedrive-vs-hubspot',
    type: 'blog',
    cluster: 'k6',
    priority: 'P1',
    metaTitle: 'Pipedrive vs HubSpot — Porównanie CRM 2026 | WeFutura',
    metaDescription: 'Pipedrive vs HubSpot — porównanie funkcji, cen, dla kogo każdy. Który CRM wybrać dla MŚP? Analiza z perspektywy wdrożeń.',
    h1: 'Pipedrive vs HubSpot — Które CRM Wybrać?',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/zapier-vs-power-automate',
    slug: 'zapier-vs-power-automate',
    type: 'blog',
    cluster: 'k6',
    priority: 'P1',
    metaTitle: 'Zapier vs Power Automate — Porównanie 2026 | WeFutura',
    metaDescription: 'Zapier vs Power Automate — które narzędzie automatyzacji wybrać? Porównanie funkcji, cen, integracji i przypadków użycia.',
    h1: 'Zapier vs Power Automate — Porównanie',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/roi-automatyzacji-jak-liczyc',
    slug: 'roi-automatyzacji-jak-liczyc',
    type: 'blog',
    cluster: 'k7',
    priority: 'P1',
    metaTitle: 'ROI Automatyzacji — Jak Liczyć Zwrot z Inwestycji | WeFutura',
    metaDescription: 'Jak liczyć ROI automatyzacji procesów — wzory, kalkulator, przykłady z liczb. Jak przekonać zarząd do inwestycji w automatyzację.',
    h1: 'ROI Automatyzacji — Jak Liczyć Zwrot z Inwestycji',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/ile-kosztuje-chatbot-dla-firmy',
    slug: 'ile-kosztuje-chatbot-dla-firmy',
    type: 'blog',
    cluster: 'k7',
    priority: 'P2',
    metaTitle: 'Ile Kosztuje Chatbot dla Firmy? Ceny 2026 | WeFutura',
    metaDescription: 'Ile kosztuje chatbot AI dla firmy w 2026? Modele cenowe, od czego zależy cena, jak oszacować budżet. Porównanie opcji.',
    h1: 'Ile Kosztuje Chatbot dla Firmy? Ceny i Modele Rozliczenia',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/ile-kosztuje-wdrozenie-crm',
    slug: 'ile-kosztuje-wdrozenie-crm',
    type: 'blog',
    cluster: 'k7',
    priority: 'P2',
    metaTitle: 'Ile Kosztuje Wdrożenie CRM? Ceny 2026 | WeFutura',
    metaDescription: 'Ile kosztuje wdrożenie CRM? Ceny licencji, konfiguracji, szkoleń i wsparcia. Porównanie popularnych systemów CRM pod kątem kosztów.',
    h1: 'Ile Kosztuje Wdrożenie CRM? Ceny i Co na Nie Wpływa',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
  {
    path: '/blog/ile-kosztuje-wdrozenie-rpa',
    slug: 'ile-kosztuje-wdrozenie-rpa',
    type: 'blog',
    cluster: 'k7',
    priority: 'P2',
    metaTitle: 'Ile Kosztuje Wdrożenie RPA? Ceny i ROI 2026 | WeFutura',
    metaDescription: 'Ile kosztuje wdrożenie RPA? Ceny, modele licencjonowania, czas wdrożenia, ROI. Kiedy wdrożenie RPA się opłaca?',
    h1: 'Ile Kosztuje Wdrożenie RPA? Ceny, ROI i Czas Zwrotu',
    parentPath: '/blog',
    parentLabel: 'Blog',
  },
];

export const allRoutes: RouteConfig[] = [
  ...pillarRoutes,
  ...supportingRoutes,
  ...industryRoutes,
  ...costRoutes,
  ...blogRoutes,
];

export function getRouteByPath(path: string): RouteConfig | undefined {
  return allRoutes.find((r) => r.path === path);
}
